### ISSUE TITLE
CI for SIMD Everywhere: Implementations of foreign SIMD instruction sets for RISC-V (and other architectures)

### ISSUE THREAD

**Issue by mr-c** [Rise-dev-appreciation/Rise-dev-appreciation#4]
**Project Name and Description**: 
The [SIMD Everywhere (`simde`) project](https://github.com/simd-everywhere/simde#simd-everywhere) provides implementations of 2,930 x86 intrinsics ([SSE, SSE2, SSE4.x, AVX, AVX2, AVX512, …](https://github.com/simd-everywhere/simde?tab=readme-ov-file#current-status)) and [6,608 ARM Neon intrinsics](https://github.com/simd-everywhere/implementation-status/blob/main/neon.md#summary). Many [free and open source projects use SIMDe](https://github.com/simd-everywhere/simde/wiki/Projects-Using-SIMDe) to add portability immediately until they get dedicated RISC-V implementations later. Debian and other Linux distributions [add SIMDe to scientific software](https://wiki.debian.org/SIMDEverywhere#Packages_Status) that would otherwise fail to compile on RISC-V.

SIMD Everywhere is featured in presentations at the 2023 and 2024 RISC-V Summits.
- [SIMD Everywhere Optimization from ARM NEON to RISC-V Vector Extensions - Ju-Hung Li, National Tsing Hua University, Taiwan & Chao-Lin Lee, PeakHills Group](https://riscvsummit2023.sched.com/event/1QUoy/simd-everywhere-optimization-from-arm-neon-to-risc-v-vector-extensions-ju-hung-li-national-tsing-hua-university-taiwan-chao-lin-lee-peakhills-group)  (paper: https://doi.org/10.48550/arXiv.2309.16509 )
- [Aggregation Optimization for SIMD Everywhere from ARM Neon to RISC-V Vector and Crypto Extensions - Jenq-Kuen Lee & Hung-Ming Lai, National Tsing-Hua University, Taiwan](https://riscvsummit2024.sched.com/event/1iYv9/aggregation-optimization-for-simd-everywhere-from-arm-neon-to-risc-v-vector-and-crypto-extensions-jenq-kuen-lee-hung-ming-lai-national-tsing-hua-university-taiwan)  (paper: https://doi.org/10.1145/3677333.3678149)

**Contribution Links**: 
- https://github.com/simd-everywhere/simde/pull/1049 ; CI for riscv64 using clang
- https://github.com/simd-everywhere/simde/commit/e5c02d455faaac5b6a71a1290e137f42a358235e ; CI gcc-12 on riscv64 with qemu
- https://github.com/simd-everywhere/simde/commit/3fa1d186d3b25e9ea2085eddbdee2c77e6cf45be docker: riscv64 cross compiling
- https://github.com/simd-everywhere/simde/releases/tag/v0.8.2 Reviewer of RVV1.0 contributions and release manager for SIMDe 0.8.2, the first release of SIMDe with optimized implementations for riscv64. I also personally tested the RVV1.0 contributions using real hardware (CanMV-K230)

**GitHub Profile Link**: https://github.com/mr-c

**Request Reward Size**: Small (500€). Added riscv-64 to the CI and cross-compiler. Reviewed the substantial RVV1.0 related contributions, tested them locally on real hardware. Release manager and solo active maintainer for SIMDe since May 2022.

I would accept additional small or large rewards in acknowledgement of my integration of SIMDe in many scientific computing codebases, either in their Debian packages, or by the scientific software developers themselves. 

**Contribution links for SIMDe integration (enabling building on RISC-V)**
Upstream patches (merged):
- skbio: [merged and released patch](https://github.com/scikit-bio/scikit-bio/pull/1709), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/python3-skbio/download), [riscv64 test results](https://ci.debian.net/packages/p/python-skbio/testing/riscv64/)
- fasta3:  [pull request](https://github.com/wrpearson/fasta36/pull/25) ; [merged commit](https://github.com/wrpearson/fasta36/commit/78b77aca69d4ecb1bcfa12aec6748f09df89a6c2), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/fasta3/download), [riscv64 test results](https://ci.debian.net/packages/f/fasta3/unstable/riscv64/)
- mmseqs2: [pull request](https://github.com/soedinglab/MMseqs2/pull/309); [merged commit](https://github.com/soedinglab/MMseqs2/commit/f5750feee432c6922879d3846c0bbb87ea0d905a), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/mmseqs2/download), [riscv64 test results](https://ci.debian.net/packages/m/mmseqs2/testing/riscv64/)
- rna-star: [pull request](https://github.com/alexdobin/STAR/pull/1163), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/rna-star/download), [riscv64 test results](https://ci.debian.net/packages/r/rna-star/testing/riscv64/)

Patched, built for riscv64, and released in Debian:
- last-align: [patch](https://sources.debian.org/src/last-align/1542-1/debian/patches/simde/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/last-align/download), [riscv64 test results](https://ci.debian.net/packages/l/last-align/testing/riscv64/)
- hisat2: [patch](https://sources.debian.org/src/hisat2/2.2.1-5/debian/patches/simde/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/hisat2/download), [riscv64 test results](https://ci.debian.net/packages/h/hisat2/testing/riscv64/)
- fermi-lite: [patch](https://sources.debian.org/src/fermi-lite/0.1+git20190320.b499514-1/debian/patches/simde/), [binary Debian  riscv64 package](https://packages.debian.org/trixie/riscv64/fml-asm/download), [riscv64 test results](https://ci.debian.net/packages/f/fermi-lite/testing/riscv64/)
- raxml: [patch](https://sources.debian.org/src/raxml/8.2.13+dfsg-1/debian/patches/simde/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/raxml/download), [riscv64 test results](https://ci.debian.net/packages/r/raxml/unstable/riscv64/)
- libssw: [patch](https://sources.debian.org/src/libssw/1.1-15/debian/patches/simde.patch/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/ssw-align/download), [riscv64 test results](https://ci.debian.net/packages/libs/libssw/testing/riscv64/)
- kmc: [patch](https://sources.debian.org/src/kmc/3.2.4+dfsg-1/debian/patches/simde/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/kmc/download), [riscv64 test results](https://ci.debian.net/packages/k/kmc/testing/riscv64/)
- ngmlr [patch](https://sources.debian.org/src/ngmlr/0.2.7+git20210816.a2a31fb+dfsg-2/debian/patches/simde.patch/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/ngmlr/download), [riscv64 test results](https://ci.debian.net/packages/n/ngmlr/testing/riscv64/)
- snap-aligner [patch](https://sources.debian.org/src/snap-aligner/2.0.3+dfsg-2/debian/patches/simde/), [binary Debian riscv64 package](https://packages.debian.org/trixie/riscv64/snap-aligner/download), [riscv64 test results](https://ci.debian.net/packages/s/snap-aligner/testing/riscv64/)

**Comment by luhenry** [comment]
Hi @mr-c, thank you for your submission! We'll take a look shortly and come back to you by end of November as outlined in https://github.com/Rise-dev-appreciation/Rise-dev-appreciation/issues/1#issue-2559691055

**Comment by mr-c** [comment]
Hello @luhenry , is there anything else you need from me concerning my application?

**Comment by luhenry** [comment]
@mr-c no, it's all good. It's been approved and you should receive the support through GitHub! Thank you again for all the work!

**Comment by mr-c** [comment]
Thank you very much @luhenry  @Rise-dev-appreciation !

**Comment by micmarti85** [comment]
Hey @mr-c we're looking to do a Developer Spotlight for participants in the RISE Developer Appreciation Pilot. We would write a short blog about you to feature on our website and socials. Is that something you'd be interested in participating in?  If so, please email outreach@riseproject.dev confirming and we'll send the details. Thanks again for your contribution!
